# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  auto_review:
    enabled: true
    drafts: false
    auto_incremental_review: true
    auto_pause_after_reviewed_commits: 5
