# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# This kernel is derived from cuDNN, NVIDIA Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""One compiled launch for the GDN-2 chain backward: chain prologue, fused H and M summary and forward state chain (M alone
from the recompute when the forward's series is passed back), G summary, reverse state chain, seeded series recompute and
bprop issued from a single host.  Every GDN-2 module compiles at ``--opt-level 2``, the chain prologue and the state
chain included (``opt_level``), so the host does too and every nested kernel is the standalone one.  Every kernel, its host and the tensor placeholder each host was compiled with
are the standalone modules' own; a buffer two hosts read through different placeholder types is passed twice, once per
type: H, M, X, G and dX (the summary, recompute and bprop hosts' torch views against the state chain's ``(1, HO, V, K)``
device views), ``cu_pieces`` (the prologue marks it at its element alignment, every other kernel at 8 bytes), ``beta``
(16 bytes in the prologue and summary, 4 in the recompute and in the bprop's guarded read) and the gate when the bprop
reads it as a linear alpha (a 4-byte view)."""

from typing import Optional

import cuda.bindings.driver as cuda
import cutlass
import cutlass.cute as cute
from cutlass.cute.runtime import from_dlpack

from cudnn.frost.buffers import DeviceView

from ..common.host import get_dtype
from ..common.piece_chain import dtype_name, launch_state_chain
from . import gdn2_bprop_f16, gdn2_bprop_summary_f16, gdn2_chain_prologue_f16, gdn2_recompute_f16, gdn2_summary_f16

chain_backward_cache = {}


@cute.jit
def chain_backward_host(
    unit_chunks: cutlass.Constexpr[int],
    b_t: cutlass.Constexpr[int],
    length_rule: cutlass.Constexpr[bool],
    fused_h_m: cutlass.Constexpr[bool],
    series: cutlass.Constexpr[bool],
    summary_cfg: cutlass.Constexpr,
    transition_cfg: cutlass.Constexpr,
    bwd_summary_cfg: cutlass.Constexpr,
    series_cfg: cutlass.Constexpr,
    bprop_cfg: cutlass.Constexpr,
    dim_v: cutlass.Constexpr[int],
    dim_k: cutlass.Constexpr[int],
    chain_rows: cutlass.Constexpr[int],
    has_seed: cutlass.Constexpr[bool],
    has_dseed: cutlass.Constexpr[bool],
    pieces: cutlass.Int32,
    heads_out: cutlass.Int32,
    num_seqs: cutlass.Int32,
    series_span_chunks: cutlass.Int32,
    checkpoint_every_n: cutlass.Int32,
    seed_every_n: cutlass.Int32,
    scale: cutlass.Float32,
    q: cute.Tensor,
    k: cute.Tensor,
    v: cute.Tensor,
    do: cute.Tensor,
    gate: cute.Tensor,
    gate_main: Optional[cute.Tensor],
    beta: cute.Tensor,
    beta_recompute: cute.Tensor,
    beta_bprop: Optional[cute.Tensor],
    w: cute.Tensor,
    a_log: Optional[cute.Tensor],
    dt_bias: Optional[cute.Tensor],
    cu_seqlens: cute.Tensor,
    cu_pieces: cute.Tensor,
    cu_pieces_main: cute.Tensor,
    main_rows: cute.Tensor,
    summary_rows: cute.Tensor,
    main_count: cute.Tensor,
    summary_count: cute.Tensor,
    work_items: cute.Tensor,
    work_items_summary: cute.Tensor,
    series_items: Optional[cute.Tensor],
    series_count: Optional[cute.Tensor],
    recompute_items: Optional[cute.Tensor],
    recompute_count: Optional[cute.Tensor],
    scheduler_all: cute.Tensor,
    scheduler_recompute: cute.Tensor,
    scheduler_m: cute.Tensor,
    scheduler_series: cute.Tensor,
    scheduler_summary: cute.Tensor,
    scheduler_bwd: cute.Tensor,
    summary_words: Optional[cute.Tensor],
    recompute_m_words: cute.Tensor,
    series_words: Optional[cute.Tensor],
    bprop_summary_words: cute.Tensor,
    bprop_words: cute.Tensor,
    checkpoints: cute.Tensor,
    seed_checkpoints: Optional[cute.Tensor],
    dq: cute.Tensor,
    dk: cute.Tensor,
    dv: cute.Tensor,
    dgate: cute.Tensor,
    dw: cute.Tensor,
    dbeta: cute.Tensor,
    state_h_summary: Optional[cute.Tensor],
    state_m_main: cute.Tensor,
    state_h_chain: Optional[cute.Tensor],
    state_m_chain: cute.Tensor,
    state_x_chain: Optional[cute.Tensor],
    seed: Optional[cute.Tensor],
    state_x_series: Optional[cute.Tensor],
    state_g: cute.Tensor,
    state_g_chain: cute.Tensor,
    state_dx_end_chain: cute.Tensor,
    state_dx_end: cute.Tensor,
    dseed: Optional[cute.Tensor],
    dstate0: Optional[cute.Tensor],
    stream: cuda.CUstream,
) -> None:
    heads_out = cutlass.Int32(gate.shape[1])
    q_ratio = heads_out // cutlass.Int32(q.shape[1])
    k_ratio = heads_out // cutlass.Int32(k.shape[1])
    v_ratio = heads_out // cutlass.Int32(v.shape[1])
    gdn2_chain_prologue_f16.chain_prologue(
        pieces,
        unit_chunks,
        b_t,
        length_rule,
        heads_out,
        series_span_chunks,
        checkpoint_every_n,
        cu_seqlens,
        cu_pieces,
        main_rows,
        summary_rows,
        main_count,
        summary_count,
        work_items,
        work_items_summary,
        scheduler_all,
        series_items,
        series_count,
        summary_words,
        None,
        recompute_m_words,
        series_words,
        None,
        bprop_summary_words,
        bprop_words,
        q,
        k,
        v,
        gate,
        beta,
        w,
        None,
        do,
        checkpoints,
        dq,
        dk,
        dv,
        dgate,
        dw,
        dbeta,
        stream,
    )
    if cutlass.const_expr(fused_h_m):
        gdn2_summary_f16.host(
            summary_cfg,
            k,
            v,
            gate,
            a_log,
            dt_bias,
            beta,
            w,
            cu_pieces_main,
            None,
            state_h_summary,
            state_m_main,
            work_items_summary,
            summary_count,
            scheduler_recompute,
            summary_words,
            stream,
        )
        launch_state_chain(
            heads_out,
            dim_v,
            dim_k,
            chain_rows,
            pieces,
            False,
            has_seed,
            False,
            False,
            num_seqs,
            state_h_chain,
            state_m_chain,
            state_x_chain,
            seed,
            None,
            None,
            main_rows,
            None,
            stream,
        )
    else:
        gdn2_recompute_f16.host(
            transition_cfg,
            k,
            k,
            gate,
            a_log,
            dt_bias,
            beta_recompute,
            k,
            cu_pieces_main,
            None,
            state_m_main,
            None,
            work_items_summary,
            summary_count,
            scheduler_m,
            recompute_m_words,
            cutlass.Int32(0),
            cutlass.Int32(0),
            stream,
        )
    gdn2_bprop_summary_f16.host(
        bwd_summary_cfg,
        q_ratio,
        k_ratio,
        a_log,
        dt_bias,
        cu_pieces_main,
        state_g,
        None,
        work_items_summary,
        summary_count,
        scheduler_summary,
        bprop_summary_words,
        scale,
        stream,
    )
    launch_state_chain(
        heads_out,
        dim_v,
        dim_k,
        chain_rows,
        pieces,
        True,
        has_dseed,
        False,
        False,
        num_seqs,
        state_g_chain,
        state_m_chain,
        state_dx_end_chain,
        dseed,
        None,
        None,
        main_rows,
        None,
        stream,
    )
    if cutlass.const_expr(series):
        gdn2_recompute_f16.host(
            series_cfg,
            k,
            v,
            gate,
            a_log,
            dt_bias,
            beta_recompute,
            w,
            cu_pieces_main,
            state_x_series,
            None,
            seed_checkpoints,
            recompute_items,
            recompute_count,
            scheduler_series,
            series_words,
            checkpoint_every_n,
            seed_every_n,
            stream,
        )
    gdn2_bprop_f16.host(
        bprop_cfg,
        q_ratio,
        k_ratio,
        v_ratio,
        checkpoints,
        a_log,
        dt_bias,
        beta_bprop,
        gate_main,
        dgate,
        dbeta,
        dw,
        cu_pieces_main,
        dstate0,
        state_dx_end,
        work_items,
        main_count,
        scheduler_bwd,
        bprop_words,
        scale,
        stream,
    )


def build_chain_backward(
    *,
    q,
    k,
    v,
    do,
    gate,
    beta,
    w,
    a_log,
    dt_bias,
    cu_seqlens,
    cu_pieces,
    main_rows,
    summary_rows,
    main_count,
    summary_count,
    work_items,
    work_items_summary,
    series_items,
    series_count,
    scheduler_all,
    scheduler_recompute,
    scheduler_m,
    scheduler_series,
    scheduler_summary,
    scheduler_bwd,
    summary_words,
    recompute_m_words,
    series_words,
    bprop_summary_words,
    bprop_words,
    checkpoints,
    seed_checkpoints,
    dq,
    dk,
    dv,
    dgate,
    dw,
    dbeta,
    state_h,
    state_m,
    state_x,
    state_g,
    state_dx_end,
    seed,
    dseed,
    dstate0,
    pieces,
    heads_out,
    num_seqs,
    unit_chunks,
    b_t,
    length_rule,
    fused_h_m,
    series,
    coarse,
    series_span_tokens,
    seed_every_n_tokens,
    log_gate,
    safe_gate,
    gate_lower_bound,
    use_qk_l2norm,
    use_beta_sigmoid,
    allow_neg_eigval,
    beta_guard,
    scale,
    chain_rows,
    device,
    num_sm,
    stream,
):
    """Compile (cached per static config) the chain backward launch over the buffers of one plan; ``pieces``, ``heads_out``
    and ``num_seqs`` are launch arguments.  The placeholders repeat the marks of the standalone modules' builds so every
    kernel compiles as it does there."""
    _HQ, DK = q.shape[1], q.shape[2]
    k.shape[1]
    _HV, DV = v.shape[1], v.shape[2]
    HO = gate.shape[1]
    if not safe_gate:
        a_log = None
        dt_bias = None
    io_dtype = get_dtype(q.dtype)
    gate_dtype = get_dtype(gate.dtype)
    gate_scale_log2 = float(gate_lower_bound) * gdn2_summary_f16.LOG2_E
    gate_main = not log_gate and not safe_gate
    beta_main = beta_guard and use_beta_sigmoid
    has_seed = seed is not None
    has_dseed = dseed is not None
    seed_name = dtype_name(seed.dtype) if has_seed else "float32"
    dseed_name = dtype_name(dseed.dtype) if has_dseed else "float32"
    key = (
        str(q.dtype),
        str(cu_seqlens.dtype),
        str(gate.dtype),
        str(beta.dtype),
        str(w.dtype),
        str(a_log.dtype) if a_log is not None else "none",
        str(dt_bias.dtype) if dt_bias is not None else "none",
        str(dstate0.dtype) if dstate0 is not None else "none",
        seed_name,
        dseed_name,
        int(device),
        int(num_sm),
        DK,
        DV,
        int(unit_chunks),
        int(b_t),
        bool(length_rule),
        bool(fused_h_m),
        bool(series),
        bool(coarse),
        bool(log_gate),
        bool(safe_gate),
        float(gate_lower_bound),
        bool(use_qk_l2norm),
        bool(use_beta_sigmoid),
        bool(allow_neg_eigval),
        bool(beta_guard),
        has_seed,
        has_dseed,
        int(chain_rows),
    )
    if key not in chain_backward_cache:
        flags = dict(
            l2norm=use_qk_l2norm,
            safe_gate=safe_gate,
            gate_scale_log2=gate_scale_log2,
            log_gate=log_gate,
            beta_sigmoid=use_beta_sigmoid,
            allow_neg_eigval=allow_neg_eigval,
            beta_guard=beta_guard,
            max_active_clusters=num_sm,
            d_k=DK,
        )
        summary_cfg = None
        transition_cfg = None
        if fused_h_m:
            summary_cfg = gdn2_summary_f16.build_cfg(io_dtype, gate_dtype, use_initial_state=False, d_v=DV, **flags)
        else:
            transition_cfg = gdn2_recompute_f16.build_cfg(
                io_dtype,
                get_dtype(state_m.dtype),
                gate_dtype,
                use_initial_state=False,
                store_final_state=True,
                enable_checkpoints=False,
                seed_checkpoints=False,
                seed_identity=True,
                v_is_zero=True,
                d_v=DK,
                **flags,
            )
        series_cfg = None
        if series:
            series_cfg = gdn2_recompute_f16.build_cfg(
                io_dtype,
                get_dtype(state_x.dtype) if not coarse else cutlass.Float32,
                gate_dtype,
                use_initial_state=not coarse,
                store_final_state=False,
                enable_checkpoints=True,
                seed_checkpoints=coarse,
                d_v=DV,
                **flags,
            )
        bwd_summary_cfg = gdn2_bprop_summary_f16.build_cfg(
            io_dtype,
            gate_dtype,
            use_dstate_in=False,
            use_dstate0=True,
            d_v=do.shape[2],
            **flags,
        )
        bprop_cfg = gdn2_bprop_f16.build_cfg(
            io_dtype,
            gate_dtype,
            use_dstate_in=True,
            use_dstate0=dstate0 is not None,
            use_initial_state=True,
            d_v=DV,
            **flags,
        )
        work_items_placeholder = from_dlpack(work_items, assumed_align=16)
        work_items_placeholder.mark_compact_shape_dynamic(mode=0, stride_order=(0, 1), divisibility=1)
        work_items_summary_placeholder = from_dlpack(work_items_summary, assumed_align=16)
        work_items_summary_placeholder.mark_compact_shape_dynamic(mode=0, stride_order=(0, 1), divisibility=1)
        series_items_placeholder = None
        if series_items is not None:
            series_items_placeholder = from_dlpack(series_items, assumed_align=16)
            series_items_placeholder.mark_compact_shape_dynamic(mode=0, stride_order=(0, 1), divisibility=1)
        chain_backward_cache[key] = cute.compile(
            chain_backward_host,
            int(unit_chunks),
            int(b_t),
            bool(length_rule),
            bool(fused_h_m),
            bool(series),
            summary_cfg,
            transition_cfg,
            bwd_summary_cfg,
            series_cfg,
            bprop_cfg,
            DV,
            DK,
            int(chain_rows),
            has_seed,
            has_dseed,
            cutlass.Int32(int(pieces)),
            cutlass.Int32(int(heads_out)),
            cutlass.Int32(int(num_seqs)),
            cutlass.Int32(int(series_span_tokens) // int(b_t)),
            cutlass.Int32(int(b_t)),
            cutlass.Int32(int(seed_every_n_tokens)),
            float(scale),
            from_dlpack(q, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(k, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(v, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(do, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(gate, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(gate, assumed_align=4).mark_layout_dynamic(leading_dim=2) if gate_main else None,
            from_dlpack(beta, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(beta, assumed_align=4).mark_layout_dynamic(leading_dim=2),
            from_dlpack(beta, assumed_align=4).mark_layout_dynamic(leading_dim=2) if beta_main else None,
            from_dlpack(w, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(a_log, assumed_align=4).mark_layout_dynamic() if a_log is not None else None,
            from_dlpack(dt_bias, assumed_align=16).mark_layout_dynamic(leading_dim=len(dt_bias.shape) - 1) if dt_bias is not None else None,
            from_dlpack(cu_seqlens, assumed_align=8 if str(cu_seqlens.dtype).endswith("int64") else 4).mark_layout_dynamic(),
            from_dlpack(cu_pieces, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(cu_pieces, assumed_align=8).mark_layout_dynamic(),
            from_dlpack(main_rows, assumed_align=16).mark_layout_dynamic(),
            from_dlpack(summary_rows, assumed_align=16).mark_layout_dynamic(),
            from_dlpack(main_count, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(summary_count, assumed_align=4).mark_layout_dynamic(),
            work_items_placeholder,
            work_items_summary_placeholder,
            series_items_placeholder,
            from_dlpack(series_count, assumed_align=4).mark_layout_dynamic() if series_count is not None else None,
            (series_items_placeholder if coarse else work_items_placeholder) if series else None,
            from_dlpack(series_count if coarse else main_count, assumed_align=4).mark_layout_dynamic() if series else None,
            from_dlpack(scheduler_all, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(scheduler_recompute, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(scheduler_m, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(scheduler_series, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(scheduler_summary, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(scheduler_bwd, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(summary_words, assumed_align=128).mark_layout_dynamic() if summary_words is not None else None,
            from_dlpack(recompute_m_words, assumed_align=128).mark_layout_dynamic(),
            from_dlpack(series_words, assumed_align=128).mark_layout_dynamic() if series_words is not None else None,
            from_dlpack(bprop_summary_words, assumed_align=128).mark_layout_dynamic(),
            from_dlpack(bprop_words, assumed_align=128).mark_layout_dynamic(),
            from_dlpack(checkpoints, assumed_align=16).mark_layout_dynamic(leading_dim=3),
            from_dlpack(seed_checkpoints, assumed_align=16).mark_layout_dynamic(leading_dim=3) if coarse else None,
            from_dlpack(dq, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(dk, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(dv, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(dgate, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(dw, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(dbeta, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(state_h, assumed_align=16).mark_layout_dynamic(leading_dim=3) if fused_h_m else None,
            from_dlpack(state_m, assumed_align=16).mark_layout_dynamic(leading_dim=3),
            from_dlpack(DeviceView(256, (1, HO, DV, DK), "float32", int(device)), assumed_align=16).mark_layout_dynamic(leading_dim=3) if fused_h_m else None,
            from_dlpack(DeviceView(256, (1, HO, DK, DK), "float32", int(device)), assumed_align=16).mark_layout_dynamic(leading_dim=3),
            from_dlpack(DeviceView(256, (1, HO, DV, DK), "float32", int(device)), assumed_align=16).mark_layout_dynamic(leading_dim=3) if fused_h_m else None,
            from_dlpack(DeviceView(256, (1, HO, DV, DK), seed_name, int(device)), assumed_align=4).mark_layout_dynamic(leading_dim=3) if has_seed else None,
            from_dlpack(state_x, assumed_align=16).mark_layout_dynamic(leading_dim=3) if series and not coarse else None,
            from_dlpack(state_g, assumed_align=16).mark_layout_dynamic(leading_dim=3),
            from_dlpack(DeviceView(256, (1, HO, DV, DK), "float32", int(device)), assumed_align=16).mark_layout_dynamic(leading_dim=3),
            from_dlpack(DeviceView(256, (1, HO, DV, DK), "float32", int(device)), assumed_align=16).mark_layout_dynamic(leading_dim=3),
            from_dlpack(state_dx_end, assumed_align=16).mark_layout_dynamic(leading_dim=3),
            from_dlpack(DeviceView(256, (1, HO, DV, DK), dseed_name, int(device)), assumed_align=4).mark_layout_dynamic(leading_dim=3) if has_dseed else None,
            from_dlpack(dstate0, assumed_align=16).mark_layout_dynamic(leading_dim=3) if dstate0 is not None else None,
            cuda.CUstream(int(stream)),
            options="--enable-tvm-ffi --opt-level 2",
        )
    return chain_backward_cache[key]


def run_chain_backward(
    compiled,
    *,
    q,
    k,
    v,
    do,
    gate,
    beta,
    w,
    a_log,
    dt_bias,
    cu_seqlens,
    cu_pieces,
    main_rows,
    summary_rows,
    main_count,
    summary_count,
    work_items,
    work_items_summary,
    series_items,
    series_count,
    scheduler_all,
    scheduler_recompute,
    scheduler_m,
    scheduler_series,
    scheduler_summary,
    scheduler_bwd,
    summary_words,
    recompute_m_words,
    series_words,
    bprop_summary_words,
    bprop_words,
    checkpoints,
    seed_checkpoints,
    dq,
    dk,
    dv,
    dgate,
    dw,
    dbeta,
    state_h,
    state_m,
    state_x,
    state_g,
    state_dx_end,
    seed,
    dseed,
    dstate0,
    pieces,
    heads_out,
    num_seqs,
    b_t,
    fused_h_m,
    series,
    coarse,
    series_span_tokens,
    seed_every_n_tokens,
    log_gate,
    safe_gate,
    use_beta_sigmoid,
    beta_guard,
    scale,
    stream,
) -> None:
    """Replay the chain backward: one crossing into the DSL for its seven launches.  The plan validated the contract at
    build, so nothing here raises."""
    compiled(
        int(pieces),
        int(heads_out),
        int(num_seqs),
        int(series_span_tokens) // int(b_t),
        int(b_t),
        int(seed_every_n_tokens),
        float(scale),
        q,
        k,
        v,
        do,
        gate,
        gate if not log_gate and not safe_gate else None,
        beta,
        beta,
        beta if beta_guard and use_beta_sigmoid else None,
        w,
        a_log if safe_gate else None,
        dt_bias if safe_gate else None,
        cu_seqlens,
        cu_pieces,
        cu_pieces,
        main_rows,
        summary_rows,
        main_count,
        summary_count,
        work_items,
        work_items_summary,
        series_items,
        series_count,
        (series_items if coarse else work_items) if series else None,
        (series_count if coarse else main_count) if series else None,
        scheduler_all,
        scheduler_recompute,
        scheduler_m,
        scheduler_series,
        scheduler_summary,
        scheduler_bwd,
        summary_words,
        recompute_m_words,
        series_words,
        bprop_summary_words,
        bprop_words,
        checkpoints,
        seed_checkpoints if coarse else None,
        dq,
        dk,
        dv,
        dgate,
        dw,
        dbeta,
        state_h if fused_h_m else None,
        state_m,
        state_h if fused_h_m else None,
        state_m,
        state_x if fused_h_m else None,
        seed,
        state_x if series and not coarse else None,
        state_g,
        state_g,
        state_dx_end,
        state_dx_end,
        dseed,
        dstate0,
        cuda.CUstream(int(stream)),
    )
