# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# This kernel is derived from cuDNN, NVIDIA Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Two compiled launches for the GDN chain backward.  The head (``--opt-level 2``, the option of the T pass, the summary and
the recompute) runs the chain prologue, the T pass, the fused H and M summary and the forward state chain (M alone from the
recompute when the forward's series is passed back) and the seeded series recompute; the tail (``--opt-level 2``, the option
of the bprop summary and the bprop) runs the G summary, the reverse state chain and the bprop.  The series recompute moves
ahead of the G summary (it depends only on the forward chain); the reverse chain is the one GDN kernel compiled at 2
while GDN's standalone level is 3 (same instruction count, one runtime division per CTA folded differently).  The bprop module is a constexpr argument: GDP at d_v = 64
runs the gdp_bprop_v64_f16 fork, whose host takes no T-pass tiles.  Every kernel, its host and the tensor placeholder each host
was compiled with are the standalone modules' own; a buffer two hosts read through different placeholder types is passed
twice, once per type (H, M and X: the summary's and recompute's mode-3 compact views against the state chain's ``(1, HO, V,
K)`` device views)."""

from typing import Optional

import cuda.bindings.driver as cuda
import cutlass
import cutlass.cute as cute
from cutlass.cute.runtime import from_dlpack

from cudnn.frost.buffers import DeviceView

from ..common.host import get_dtype
from ..common.piece_chain import dtype_name, launch_state_chain
from . import gdn_bprop_summary_f16, gdn_chain_prologue_f16, gdn_recompute_f16, gdn_summary_f16, gdn_tinv_f16

chain_backward_cache = {}


@cute.jit
def chain_backward_head_host(
    unit_chunks: cutlass.Constexpr[int],
    b_t: cutlass.Constexpr[int],
    expand_num: cutlass.Constexpr[int],
    length_rule: cutlass.Constexpr[bool],
    compact_qdo: cutlass.Constexpr[bool],
    summary_q_step: cutlass.Constexpr[int],
    fused_h_m: cutlass.Constexpr[bool],
    series: cutlass.Constexpr[bool],
    tinv_cfg: cutlass.Constexpr,
    summary_cfg: cutlass.Constexpr,
    transition_cfg: cutlass.Constexpr,
    series_cfg: cutlass.Constexpr,
    dim_v: cutlass.Constexpr[int],
    dim_k: cutlass.Constexpr[int],
    chain_rows: cutlass.Constexpr[int],
    has_seed: cutlass.Constexpr[bool],
    pieces: cutlass.Int32,
    heads_out: cutlass.Int32,
    num_seqs: cutlass.Int32,
    series_span_chunks: cutlass.Int32,
    checkpoint_every_n: cutlass.Int32,
    seed_every_n: cutlass.Int32,
    q: cute.Tensor,
    k: cute.Tensor,
    v: cute.Tensor,
    do: cute.Tensor,
    gate: cute.Tensor,
    beta: cute.Tensor,
    a_log: Optional[cute.Tensor],
    dt_bias: Optional[cute.Tensor],
    cu_seqlens: cute.Tensor,
    cu_pieces: cute.Tensor,
    main_rows: cute.Tensor,
    summary_rows: cute.Tensor,
    main_count: cute.Tensor,
    summary_count: cute.Tensor,
    work_items: cute.Tensor,
    work_items_summary: cute.Tensor,
    series_items: Optional[cute.Tensor],
    series_count: Optional[cute.Tensor],
    recompute_items: Optional[cute.Tensor],
    recompute_count: Optional[cute.Tensor],
    scheduler_all: cute.Tensor,
    scheduler_recompute: cute.Tensor,
    scheduler_m: cute.Tensor,
    scheduler_series: cute.Tensor,
    tinv_words: cute.Tensor,
    tinv_rows: cute.Tensor,
    tinv_row_count: cute.Tensor,
    summary_words: Optional[cute.Tensor],
    recompute_m_words: cute.Tensor,
    series_words: Optional[cute.Tensor],
    bprop_summary_words: cute.Tensor,
    bprop_words: cute.Tensor,
    checkpoints: cute.Tensor,
    dq: cute.Tensor,
    dk: cute.Tensor,
    dv: cute.Tensor,
    summary_q: cute.Tensor,
    summary_do: cute.Tensor,
    tinv: cute.Tensor,
    state_h_summary: Optional[cute.Tensor],
    state_m_main: cute.Tensor,
    state_h_chain: Optional[cute.Tensor],
    state_m_chain: Optional[cute.Tensor],
    state_x_chain: Optional[cute.Tensor],
    seed: Optional[cute.Tensor],
    state_x_series: Optional[cute.Tensor],
    seed_checkpoints: Optional[cute.Tensor],
    stream: cuda.CUstream,
) -> None:
    gdn_chain_prologue_f16.chain_prologue(
        pieces,
        unit_chunks,
        b_t,
        expand_num,
        length_rule,
        heads_out,
        compact_qdo,
        summary_q_step,
        series_span_chunks,
        checkpoint_every_n,
        cu_seqlens,
        cu_pieces,
        main_rows,
        summary_rows,
        main_count,
        summary_count,
        work_items,
        work_items_summary,
        scheduler_all,
        series_items,
        series_count,
        tinv_words,
        tinv_rows,
        tinv_row_count,
        summary_words,
        None,
        recompute_m_words,
        series_words,
        None,
        bprop_summary_words,
        bprop_words,
        q,
        k,
        v,
        None,
        do,
        checkpoints,
        dq,
        dk,
        dv,
        summary_q,
        summary_do,
        tinv,
        stream,
    )
    gdn_tinv_f16.host(tinv_cfg, False, k, tinv_words, gate, a_log, dt_bias, beta, cu_pieces, tinv, tinv_rows, tinv_row_count, stream)
    if cutlass.const_expr(fused_h_m):
        gdn_summary_f16.host(
            summary_cfg,
            k,
            v,
            gate,
            a_log,
            dt_bias,
            cu_pieces,
            tinv,
            None,
            state_h_summary,
            state_m_main,
            work_items_summary,
            summary_count,
            scheduler_recompute,
            summary_words,
            stream,
        )
        launch_state_chain(
            heads_out,
            dim_v,
            dim_k,
            chain_rows,
            pieces,
            False,
            has_seed,
            False,
            False,
            num_seqs,
            state_h_chain,
            state_m_chain,
            state_x_chain,
            seed,
            None,
            None,
            main_rows,
            None,
            stream,
        )
    else:
        gdn_recompute_f16.host(
            transition_cfg,
            k,
            k,
            gate,
            a_log,
            dt_bias,
            cu_pieces,
            None,
            state_m_main,
            None,
            tinv,
            work_items_summary,
            summary_count,
            scheduler_m,
            cutlass.Int32(0),
            cutlass.Int32(0),
            recompute_m_words,
            stream,
        )
    if cutlass.const_expr(series):
        gdn_recompute_f16.host(
            series_cfg,
            k,
            v,
            gate,
            a_log,
            dt_bias,
            cu_pieces,
            state_x_series,
            None,
            seed_checkpoints,
            tinv,
            recompute_items,
            recompute_count,
            scheduler_series,
            checkpoint_every_n,
            seed_every_n,
            series_words,
            stream,
        )


@cute.jit
def chain_backward_tail_host(
    bprop: cutlass.Constexpr,
    compact_qdo: cutlass.Constexpr[bool],
    summary_cfg: cutlass.Constexpr,
    bprop_cfg: cutlass.Constexpr,
    dim_v: cutlass.Constexpr[int],
    dim_k: cutlass.Constexpr[int],
    chain_rows: cutlass.Constexpr[int],
    has_seed: cutlass.Constexpr[bool],
    pieces: cutlass.Int32,
    heads_out: cutlass.Int32,
    num_seqs: cutlass.Int32,
    scale: cutlass.Float32,
    summary_q: cute.Tensor,
    k: cute.Tensor,
    gate: cute.Tensor,
    a_log: Optional[cute.Tensor],
    dt_bias: Optional[cute.Tensor],
    summary_do: cute.Tensor,
    cu_pieces: cute.Tensor,
    main_rows: cute.Tensor,
    state_g: cute.Tensor,
    state_m_chain: cute.Tensor,
    state_dx_end: cute.Tensor,
    seed: Optional[cute.Tensor],
    q: cute.Tensor,
    v: cute.Tensor,
    beta: cute.Tensor,
    do: cute.Tensor,
    dq: cute.Tensor,
    dk: cute.Tensor,
    dv: cute.Tensor,
    dgate: cute.Tensor,
    dbeta: cute.Tensor,
    dstate0: Optional[cute.Tensor],
    inv_q: Optional[cute.Tensor],
    inv_k: Optional[cute.Tensor],
    tinv: cute.Tensor,
    work_items_summary: cute.Tensor,
    summary_count: cute.Tensor,
    scheduler_summary: cute.Tensor,
    bprop_summary_words: cute.Tensor,
    work_items: cute.Tensor,
    main_count: cute.Tensor,
    scheduler_bwd: cute.Tensor,
    bprop_words: cute.Tensor,
    stream: cuda.CUstream,
) -> None:
    gdn_bprop_summary_f16.host(
        summary_cfg,
        summary_q,
        k,
        gate,
        a_log,
        dt_bias,
        summary_do,
        cu_pieces,
        state_g,
        None,
        tinv,
        work_items_summary,
        summary_count,
        scheduler_summary,
        scale,
        bprop_summary_words,
        stream,
    )
    launch_state_chain(
        heads_out,
        dim_v,
        dim_k,
        chain_rows,
        pieces,
        True,
        has_seed,
        False,
        False,
        num_seqs,
        state_g,
        state_m_chain,
        state_dx_end,
        seed,
        None,
        None,
        main_rows,
        None,
        stream,
    )
    if cutlass.const_expr(compact_qdo):
        bprop.host(
            bprop_cfg,
            q,
            k,
            v,
            gate,
            a_log,
            dt_bias,
            beta,
            dgate,
            dbeta,
            do,
            dq,
            dk,
            dv,
            cu_pieces,
            dstate0,
            state_dx_end,
            inv_q,
            inv_k,
            work_items,
            main_count,
            scheduler_bwd,
            scale,
            bprop_words,
            stream,
        )
    else:
        bprop.host(
            bprop_cfg,
            q,
            k,
            v,
            gate,
            a_log,
            dt_bias,
            beta,
            dgate,
            dbeta,
            do,
            dq,
            dk,
            dv,
            cu_pieces,
            dstate0,
            state_dx_end,
            inv_q,
            inv_k,
            tinv,
            work_items,
            main_count,
            scheduler_bwd,
            scale,
            bprop_words,
            stream,
        )


def build_chain_backward(
    *,
    bprop_module,
    q,
    k,
    v,
    do,
    gate,
    beta,
    a_log,
    dt_bias,
    cu_seqlens,
    cu_pieces,
    main_rows,
    summary_rows,
    main_count,
    summary_count,
    work_items,
    work_items_summary,
    series_items,
    series_count,
    scheduler_all,
    scheduler_recompute,
    scheduler_m,
    scheduler_series,
    scheduler_summary,
    scheduler_bwd,
    tinv_words,
    tinv_rows,
    tinv_row_count,
    summary_words,
    recompute_m_words,
    series_words,
    bprop_summary_words,
    bprop_words,
    checkpoints,
    seed_checkpoints,
    dq,
    dk,
    dv,
    dgate,
    dbeta,
    summary_q,
    summary_do,
    tinv,
    state_h,
    state_m,
    state_x,
    state_g,
    state_dx_end,
    seed,
    dseed,
    dstate0,
    inv_q,
    inv_k,
    pieces,
    heads_out,
    num_seqs,
    unit_chunks,
    b_t,
    expand_num,
    length_rule,
    compact_qdo,
    summary_q_step,
    fused_h_m,
    series,
    coarse,
    series_span_tokens,
    seed_every_n_tokens,
    log_gate,
    safe_gate,
    use_beta_sigmoid,
    allow_neg_eigval,
    scale,
    chain_rows,
    device,
    num_sm,
    stream,
):
    """Compile (cached per static config) the head and tail launches of the chain backward over the buffers of one plan;
    ``pieces``, ``heads_out`` and ``num_seqs`` are launch arguments.  The placeholders repeat the marks of the standalone
    modules' builds so every kernel compiles as it does there."""
    HQ, DK = q.shape[1], q.shape[2]
    HK = k.shape[1]
    HV, DV = v.shape[1], v.shape[2]
    HO = gate.shape[1]
    if not safe_gate:
        a_log = None
        dt_bias = None
    io_dtype = get_dtype(q.dtype)
    has_seed = seed is not None
    has_dseed = dseed is not None
    seed_name = dtype_name(seed.dtype) if has_seed else "float32"
    dseed_name = dtype_name(dseed.dtype) if has_dseed else "float32"
    cu_align = 8 if str(cu_seqlens.dtype).endswith("int64") else 4
    key = (
        str(q.dtype),
        str(cu_seqlens.dtype),
        str(gate.dtype),
        str(beta.dtype),
        str(a_log.dtype) if a_log is not None else "none",
        str(dt_bias.dtype) if dt_bias is not None else "none",
        str(state_x.dtype) if state_x is not None else "none",
        str(dstate0.dtype) if dstate0 is not None else "none",
        seed_name,
        dseed_name,
        int(device),
        int(num_sm),
        DK,
        DV,
        summary_q.shape[1],
        summary_do.shape[1],
        int(unit_chunks),
        int(b_t),
        int(expand_num),
        bool(length_rule),
        bool(compact_qdo),
        int(summary_q_step),
        bool(fused_h_m),
        bool(series),
        bool(coarse),
        bool(log_gate),
        bool(safe_gate),
        bool(use_beta_sigmoid),
        bool(allow_neg_eigval),
        inv_q is not None,
        has_seed,
        has_dseed,
        int(chain_rows),
        bprop_module.__name__,
    )
    if key not in chain_backward_cache:
        tinv_cfg = gdn_tinv_f16.build_cfg(
            io_dtype,
            num_sm=num_sm,
            log_gate=log_gate,
            safe_gate=safe_gate,
            beta_sigmoid=use_beta_sigmoid,
            allow_neg_eigval=allow_neg_eigval,
            d_k=DK,
            expand_num=expand_num,
        )
        summary_cfg = None
        transition_cfg = None
        if fused_h_m:
            summary_cfg = gdn_summary_f16.build_cfg(
                io_dtype,
                get_dtype(state_h.dtype),
                max_active_clusters=num_sm,
                use_initial_state=False,
                log_gate=log_gate,
                safe_gate=safe_gate,
                d_k=DK,
                d_v=DV,
                expand_num=expand_num,
            )
        else:
            transition_cfg = gdn_recompute_f16.build_cfg(
                io_dtype,
                get_dtype(state_m.dtype),
                max_active_clusters=num_sm,
                use_initial_state=False,
                store_final_state=True,
                enable_checkpoints=False,
                seed_checkpoints=False,
                log_gate=log_gate,
                safe_gate=safe_gate,
                seed_identity=True,
                v_is_zero=True,
                d_k=DK,
                d_v=DK,
                expand_num=expand_num,
            )
        series_cfg = None
        if series:
            series_cfg = gdn_recompute_f16.build_cfg(
                io_dtype,
                get_dtype(state_x.dtype) if not coarse else cutlass.Float32,
                max_active_clusters=num_sm,
                use_initial_state=not coarse,
                store_final_state=False,
                enable_checkpoints=True,
                seed_checkpoints=coarse,
                log_gate=log_gate,
                safe_gate=safe_gate,
                d_k=DK,
                d_v=DV,
                expand_num=expand_num,
            )
        bwd_summary_cfg = gdn_bprop_summary_f16.build_cfg(
            io_dtype,
            max_active_clusters=num_sm,
            use_dstate_in=False,
            log_gate=log_gate,
            safe_gate=safe_gate,
            d_k=DK,
            d_v=DV,
            expand_num=expand_num,
        )
        bprop_cfg = bprop_module.build_cfg(
            io_dtype,
            max_active_clusters=num_sm,
            use_initial_state=True,
            use_dstate_in=True,
            use_dstate0=dstate0 is not None,
            log_gate=log_gate,
            safe_gate=safe_gate,
            beta_sigmoid=use_beta_sigmoid,
            allow_neg_eigval=allow_neg_eigval,
            fused_l2norm=inv_q is not None,
            d_k=DK,
            d_v=DV,
            expand_num=expand_num,
            **({} if compact_qdo else dict(tinv_source="gmem")),
        )

        work_items_placeholder = from_dlpack(work_items, assumed_align=16)
        work_items_placeholder.mark_compact_shape_dynamic(mode=0, stride_order=(0, 1), divisibility=1)
        work_items_summary_placeholder = from_dlpack(work_items_summary, assumed_align=16)
        work_items_summary_placeholder.mark_compact_shape_dynamic(mode=0, stride_order=(0, 1), divisibility=1)
        series_items_placeholder = None
        if series_items is not None:
            series_items_placeholder = from_dlpack(series_items, assumed_align=16)
            series_items_placeholder.mark_compact_shape_dynamic(mode=0, stride_order=(0, 1), divisibility=1)
        state_h_placeholder = None
        if fused_h_m:
            state_h_placeholder = from_dlpack(state_h, assumed_align=16)
            state_h_placeholder.mark_layout_dynamic().mark_compact_shape_dynamic(mode=3, stride_order=(0, 1, 2, 3), divisibility=DK)
        state_m_placeholder = from_dlpack(state_m, assumed_align=16)
        state_m_placeholder.mark_layout_dynamic().mark_compact_shape_dynamic(mode=3, stride_order=(0, 1, 2, 3), divisibility=DK)
        state_x_placeholder = None
        if series and not coarse:
            state_x_placeholder = from_dlpack(state_x, assumed_align=16)
            state_x_placeholder.mark_layout_dynamic().mark_compact_shape_dynamic(mode=3, stride_order=(0, 1, 2, 3), divisibility=DK)
        head = cute.compile(
            chain_backward_head_host,
            int(unit_chunks),
            int(b_t),
            int(expand_num),
            bool(length_rule),
            bool(compact_qdo),
            int(summary_q_step),
            bool(fused_h_m),
            bool(series),
            tinv_cfg,
            summary_cfg,
            transition_cfg,
            series_cfg,
            DV,
            DK,
            int(chain_rows),
            has_seed,
            cutlass.Int32(int(pieces)),
            cutlass.Int32(int(heads_out)),
            cutlass.Int32(int(num_seqs)),
            cutlass.Int32(int(series_span_tokens) // int(b_t)),
            cutlass.Int32(int(b_t)),
            cutlass.Int32(int(seed_every_n_tokens)),
            from_dlpack(q, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(k, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(v, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(do, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(gate, assumed_align=16).mark_layout_dynamic(leading_dim=1),
            from_dlpack(beta, assumed_align=16).mark_layout_dynamic(leading_dim=1),
            from_dlpack(a_log, assumed_align=4).mark_layout_dynamic() if a_log is not None else None,
            from_dlpack(dt_bias, assumed_align=4).mark_layout_dynamic(leading_dim=len(dt_bias.shape) - 1) if dt_bias is not None else None,
            from_dlpack(cu_seqlens, assumed_align=cu_align).mark_layout_dynamic(),
            from_dlpack(cu_pieces, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(main_rows, assumed_align=16).mark_layout_dynamic(),
            from_dlpack(summary_rows, assumed_align=16).mark_layout_dynamic(),
            from_dlpack(main_count, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(summary_count, assumed_align=4).mark_layout_dynamic(),
            work_items_placeholder,
            work_items_summary_placeholder,
            series_items_placeholder,
            from_dlpack(series_count, assumed_align=4).mark_layout_dynamic() if series_count is not None else None,
            (series_items_placeholder if coarse else work_items_placeholder) if series else None,
            from_dlpack(series_count if coarse else main_count, assumed_align=4).mark_layout_dynamic() if series else None,
            from_dlpack(scheduler_all, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(scheduler_recompute, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(scheduler_m, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(scheduler_series, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(tinv_words, assumed_align=128).mark_layout_dynamic(),
            from_dlpack(tinv_rows, assumed_align=16).mark_layout_dynamic(leading_dim=1),
            from_dlpack(tinv_row_count, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(summary_words, assumed_align=128).mark_layout_dynamic() if summary_words is not None else None,
            from_dlpack(recompute_m_words, assumed_align=128).mark_layout_dynamic(),
            from_dlpack(series_words, assumed_align=128).mark_layout_dynamic() if series_words is not None else None,
            from_dlpack(bprop_summary_words, assumed_align=128).mark_layout_dynamic(),
            from_dlpack(bprop_words, assumed_align=128).mark_layout_dynamic(),
            from_dlpack(checkpoints, assumed_align=16).mark_layout_dynamic(leading_dim=3),
            from_dlpack(dq, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(dk, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(dv, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(summary_q, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(summary_do, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(tinv, assumed_align=128).mark_layout_dynamic(leading_dim=3),
            state_h_placeholder,
            state_m_placeholder,
            from_dlpack(DeviceView(256, (1, HO, DV, DK), "float32", int(device)), assumed_align=16).mark_layout_dynamic(leading_dim=3) if fused_h_m else None,
            from_dlpack(DeviceView(256, (1, HO, DK, DK), "float32", int(device)), assumed_align=16).mark_layout_dynamic(leading_dim=3) if fused_h_m else None,
            from_dlpack(DeviceView(256, (1, HO, DV, DK), "float32", int(device)), assumed_align=16).mark_layout_dynamic(leading_dim=3) if fused_h_m else None,
            from_dlpack(DeviceView(256, (1, HO, DV, DK), seed_name, int(device)), assumed_align=4).mark_layout_dynamic(leading_dim=3) if has_seed else None,
            state_x_placeholder,
            from_dlpack(seed_checkpoints, assumed_align=16).mark_layout_dynamic(leading_dim=3) if coarse else None,
            cuda.CUstream(int(stream)),
            options="--enable-tvm-ffi --opt-level 2",
        )
        tail = cute.compile(
            chain_backward_tail_host,
            bprop_module,
            bool(compact_qdo),
            bwd_summary_cfg,
            bprop_cfg,
            DV,
            DK,
            int(chain_rows),
            has_dseed,
            cutlass.Int32(int(pieces)),
            cutlass.Int32(int(heads_out)),
            cutlass.Int32(int(num_seqs)),
            float(scale),
            from_dlpack(summary_q, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(k, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(gate, assumed_align=16).mark_layout_dynamic(leading_dim=1),
            from_dlpack(a_log, assumed_align=4).mark_layout_dynamic() if a_log is not None else None,
            from_dlpack(dt_bias, assumed_align=4).mark_layout_dynamic(leading_dim=len(dt_bias.shape) - 1) if dt_bias is not None else None,
            from_dlpack(summary_do, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(cu_pieces, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(main_rows, assumed_align=16).mark_layout_dynamic(),
            from_dlpack(state_g, assumed_align=16).mark_layout_dynamic(leading_dim=3),
            from_dlpack(DeviceView(256, (1, HO, DK, DK), "float32", int(device)), assumed_align=16).mark_layout_dynamic(leading_dim=3),
            from_dlpack(state_dx_end, assumed_align=16).mark_layout_dynamic(leading_dim=3),
            from_dlpack(DeviceView(256, (1, HO, DV, DK), dseed_name, int(device)), assumed_align=4).mark_layout_dynamic(leading_dim=3) if has_dseed else None,
            from_dlpack(q, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(v, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(beta, assumed_align=16).mark_layout_dynamic(leading_dim=1),
            from_dlpack(do, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(dq, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(dk, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(dv, assumed_align=16).mark_layout_dynamic(leading_dim=2),
            from_dlpack(dgate, assumed_align=16).mark_layout_dynamic(leading_dim=1),
            from_dlpack(dbeta, assumed_align=16).mark_layout_dynamic(leading_dim=1),
            from_dlpack(dstate0, assumed_align=16).mark_layout_dynamic(leading_dim=3) if dstate0 is not None else None,
            from_dlpack(inv_q, assumed_align=4).mark_layout_dynamic(leading_dim=1) if inv_q is not None else None,
            from_dlpack(inv_k, assumed_align=4).mark_layout_dynamic(leading_dim=1) if inv_k is not None else None,
            from_dlpack(tinv, assumed_align=128).mark_layout_dynamic(leading_dim=3),
            work_items_summary_placeholder,
            from_dlpack(summary_count, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(scheduler_summary, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(bprop_summary_words, assumed_align=128).mark_layout_dynamic(),
            work_items_placeholder,
            from_dlpack(main_count, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(scheduler_bwd, assumed_align=4).mark_layout_dynamic(),
            from_dlpack(bprop_words, assumed_align=128).mark_layout_dynamic(),
            cuda.CUstream(int(stream)),
            options="--enable-tvm-ffi --opt-level 2",
        )
        chain_backward_cache[key] = (head, tail)
    return chain_backward_cache[key]


def run_chain_backward(
    compiled,
    *,
    q,
    k,
    v,
    do,
    gate,
    beta,
    a_log,
    dt_bias,
    cu_seqlens,
    cu_pieces,
    main_rows,
    summary_rows,
    main_count,
    summary_count,
    work_items,
    work_items_summary,
    series_items,
    series_count,
    scheduler_all,
    scheduler_recompute,
    scheduler_m,
    scheduler_series,
    scheduler_summary,
    scheduler_bwd,
    tinv_words,
    tinv_rows,
    tinv_row_count,
    summary_words,
    recompute_m_words,
    series_words,
    bprop_summary_words,
    bprop_words,
    checkpoints,
    seed_checkpoints,
    dq,
    dk,
    dv,
    dgate,
    dbeta,
    summary_q,
    summary_do,
    tinv,
    state_h,
    state_m,
    state_x,
    state_g,
    state_dx_end,
    seed,
    dseed,
    dstate0,
    inv_q,
    inv_k,
    pieces,
    heads_out,
    num_seqs,
    b_t,
    compact_qdo,
    fused_h_m,
    series,
    coarse,
    series_span_tokens,
    seed_every_n_tokens,
    scale,
    stream,
) -> None:
    """Replay the chain backward: two crossings into the DSL for its eight launches.  The plan validated the contract at
    build, so nothing here raises."""
    head, tail = compiled
    cu_stream = cuda.CUstream(int(stream))
    head(
        int(pieces),
        int(heads_out),
        int(num_seqs),
        int(series_span_tokens) // int(b_t),
        int(b_t),
        int(seed_every_n_tokens),
        q,
        k,
        v,
        do,
        gate,
        beta,
        a_log,
        dt_bias,
        cu_seqlens,
        cu_pieces,
        main_rows,
        summary_rows,
        main_count,
        summary_count,
        work_items,
        work_items_summary,
        series_items,
        series_count,
        (series_items if coarse else work_items) if series else None,
        (series_count if coarse else main_count) if series else None,
        scheduler_all,
        scheduler_recompute,
        scheduler_m,
        scheduler_series,
        tinv_words,
        tinv_rows,
        tinv_row_count,
        summary_words,
        recompute_m_words,
        series_words,
        bprop_summary_words,
        bprop_words,
        checkpoints,
        dq,
        dk,
        dv,
        summary_q,
        summary_do,
        tinv,
        state_h if fused_h_m else None,
        state_m,
        state_h if fused_h_m else None,
        state_m if fused_h_m else None,
        state_x if fused_h_m else None,
        seed,
        state_x if series and not coarse else None,
        seed_checkpoints if coarse else None,
        cu_stream,
    )
    tail(
        int(pieces),
        int(heads_out),
        int(num_seqs),
        float(scale),
        summary_q,
        k,
        gate,
        a_log,
        dt_bias,
        summary_do,
        cu_pieces,
        main_rows,
        state_g,
        state_m,
        state_dx_end,
        dseed,
        q,
        v,
        beta,
        do,
        dq,
        dk,
        dv,
        dgate,
        dbeta,
        dstate0,
        inv_q,
        inv_k,
        tinv,
        work_items_summary,
        summary_count,
        scheduler_summary,
        bprop_summary_words,
        work_items,
        main_count,
        scheduler_bwd,
        bprop_words,
        cu_stream,
    )
