# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Kimi Delta Attention (KDA) chunked linear-attention prefill for Hopper (sm90).

PREP (grid = (gap-safe_global_chunks, H), 128 thr) -- fully parallel over
16-token chunks.  A CTA maps its virtual packed-chunk coordinate through
cu_seqlens, so uneven and zero-length batches do not require an N-times
max-sequence launch bound.  Per chunk it builds the pieces of the affine operator
in UT/WY form.  BT = 16 plus "every exponent that reaches exp2 is <= 0" keeps
the production gate (g in (-5,0), mean -2.5) inside fp32 range:

    G   = chunk-local inclusive cumsum of g            (<= 0, decreasing)
    E   = exp(G) in (0,1] ,  a = E[L-1]
    kw  = k * E                                        (<= |k|)
    ub  = beta * k / E                                 (<= e^{|G_L|})
    kg  = ub * a = beta*k*exp(G_L - G)                 (<= |k|)
    qg  = scale * q * E
    T   = I + strict_lower(kw @ ub^T) ,  Z = tril(qg @ ub^T, 0)
    wt  = T^{-1} kw ,  ut = T^{-1} v                   (forward substitution)

SCAN (grid = (N, H), 256 thr = 2 warpgroups) -- sequential over chunks with the
state kept TRANSPOSED as an fp32 wgmma accumulator St = S^T [Dv=128, Dk=128],
which is exactly the V-major layout of initial_state / final_state:

    Rt  = ut^T + St @ (-wt)^T      (M=128, N=16,  K=128)
    Ot  = St @ qg^T                (M=128, N=16,  K=128)
    Ot += Rt @ Z^T                 (M=128, N=16,  K=16)
    St  = St*a + Rt @ kg           (M=128, N=128, K=16)

Transposing the state makes every wgmma full-M (128 rows) instead of the 16-row
shape the untransposed recurrence would give.  Both St and Rt are fed to WGMMA
as REGISTER A-operands (OperandSource.RMEM), so the [128,128] state never moves
through shared memory -- that removes ~96 KB of SMEM traffic and two CTA
barriers from every step of the serial chain.

Provenance
----------
Generated by a Kernel Factory campaign on the ``kda_chunked_prefill_sm90``
operation (campaign ``m58kq4q63h0zn893p6sxywe9g4``, kernel
``4e60c30a6b60c3d3140f59e25e65aa265ebcba7fae8531eabdef728083d87ad1``,
solution ``kda_sm90_runtime_partial_tail_v64``).

Verified on H100 80GB HBM3 (SXM) at the production gate
(``gate_lower_bound = -5``) with a non-zero ``initial_state``, geomean over ten
shapes, two independent passes:

===================  ===========  ==========  ==========
metric               this kernel  FlashKDA    ratio
===================  ===========  ==========  ==========
per-call             368.5 us     438.7 us    1.19x
pipelined            257.5 us     398.2 us    1.54x
===================  ===========  ==========  ==========

Accuracy against an fp64 oracle is 5.0e-03 to 1.0e-02, against FlashKDA's own
7.5e-03 to 1.0e-02 on the same inputs.

The predecessor vendored here used ``BT = 64`` with a single mid-chunk anchor and
returned 100% NaN at ``gate_lower_bound = -5``: a 64-token chunk spans ~118 in
the exponent there and fp32 overflows at 88. Per-sub-block anchoring cannot fix
that, because KDA's decay is per-key-channel, so the cross-block correction
``exp(r_j[d] - r_i[d])`` lives inside the channel sum of ``Wn @ U^T`` and no
post-matmul scalar removes it. Every token in one matmul must share an anchor,
which forces ``BT <= 16``. This kernel goes further and arranges for every
exponent reaching ``exp2`` to be ``<= 0``, so the exponential can only underflow
to zero -- overflow is structurally impossible rather than merely budgeted.
"""

import os

os.environ.setdefault("CUTE_DSL_ARCH", "sm_90a")

import math

import torch

import cutlass
import cutlass.cute as cute
import cutlass.pipeline as pipeline
import cutlass.utils as utils
import cutlass.utils.hopper_helpers as hh
from cutlass.cute.nvgpu import cpasync, warpgroup
from cutlass.cute.runtime import from_dlpack
import cuda.bindings.driver as cudadrv

BF16 = cutlass.BFloat16
F32 = cutlass.Float32
I32 = cutlass.Int32

LOG2E = 1.4426950408889634
DIM = 128
NSTAGE = 6
NSTC = 3
VSPLIT = 8
TXBYTES = 4 * (16 * 128 * 2) + 16 * 16 * 2 + 128 * 4


def c2a_layout(c, a):
    return cute.make_layout(
        (a, c.shape[1], (c.shape[2], cute.size(c, mode=[0]) // cute.size(a))),
        stride=(
            c.stride[0],
            c.stride[1],
            (c.stride[2], cute.size(a, mode=[2]) * c.stride[0][2]),
        ),
    )


@cute.jit
def acc_to_a(acc, a_shape):
    operand = cute.make_rmem_tensor_like(c2a_layout(acc.layout, a_shape), BF16)
    as_acc = cute.make_tensor(operand.iterator, acc.layout)
    as_acc.store(acc.load().to(BF16))
    return operand


@cute.jit
def bf16_c_to_a(frag, a_shape):
    """Alias a packed BF16 WGMMA-C fragment as an RMEM A operand."""
    return cute.make_tensor(frag.iterator, c2a_layout(frag.layout, a_shape))


# ---------------------------------------------------------------------------
# PREP
# ---------------------------------------------------------------------------
@cute.kernel
def prep_kernel(
    mQ: cute.Tensor,
    mK: cute.Tensor,
    mV: cute.Tensor,
    mG: cute.Tensor,
    mBeta: cute.Tensor,
    mCu: cute.Tensor,
    mMW: cute.Tensor,
    mQG: cute.Tensor,
    mKG: cute.Tensor,
    mUT: cute.Tensor,
    mZ: cute.Tensor,
    mAv: cute.Tensor,
    tiled_mma: cute.TiledMma,
    scale: cutlass.Constexpr,
    nseq: cutlass.Constexpr,
    nch: cutlass.Constexpr,
    nheads: cutlass.Constexpr,
    PREP_MODE: cutlass.Constexpr,
):
    tidx, _, _ = cute.arch.thread_idx()
    hq, prep_idx, _ = cute.arch.block_idx()

    if cutlass.const_expr(PREP_MODE == 2):
        # A separate tail launch maps block-y directly to the sequence.  This
        # keeps the common full-chunk kernel free of clamp/mask arithmetic.
        sq = prep_idx
        s0 = mCu[sq]
        s1 = mCu[sq + 1]
        ncs = (s1 - s0 + 15) // 16
        lc = ncs - 1
        gcb = s0 // 16 + sq + lc
        active = (s1 - s0) % 16 != 0
    else:
        # Sequence s owns the disjoint virtual-chunk interval beginning at
        # floor(cu[s] / 16) + s.  Alignment gaps fail the active guard.
        gcb = prep_idx
        sq = I32(0)
        for si in cutlass.range_constexpr(1, nseq):
            cb_base_si = mCu[si] // 16 + si
            sq = sq + I32(gcb >= cb_base_si)
        s0 = mCu[sq]
        s1 = mCu[sq + 1]
        ncs = (s1 - s0 + 15) // 16
        lc = gcb - (s0 // 16 + sq)
        if cutlass.const_expr(PREP_MODE == 1):
            active = lc < (s1 - s0) // 16
        else:
            active = lc < ncs

    if active:
        sA_layout = cute.slice_(
            hh.make_smem_layout_a(utils.LayoutEnum.ROW_MAJOR, (64, 16, 128), BF16, 1),
            (None, None, 0),
        )
        sB_layout = cute.slice_(
            hh.make_smem_layout_b(utils.LayoutEnum.ROW_MAJOR, (64, 16, 128), BF16, 1),
            (None, None, 0),
        )
        smem = utils.SmemAllocator()
        sA = smem.allocate_tensor(BF16, sA_layout.outer, byte_alignment=1024, swizzle=sA_layout.inner)
        sB = smem.allocate_tensor(BF16, sB_layout.outer, byte_alignment=1024, swizzle=sB_layout.inner)
        sM = smem.allocate_tensor(F32, cute.make_layout((64, 16)), byte_alignment=16)

        tok0 = s0 + lc * 16
        cb = gcb * nheads + hq
        d = tidx

        # One-dimensional views over this chunk's 16 tokens with a CONSTEXPR
        # stride, and a chunk-hoisted tail clamp.  NCU names ALU as PREP's top
        # pipeline: per token the old form redid a 3-D index (IMAD + adds) for
        # each of q/k/v/g/beta plus a two-operand clamp and mask.  Here the
        # channel/head part of the address is folded into the base pointer once.
        if cutlass.const_expr(PREP_MODE == 1):
            nvm1 = I32(15)
        else:
            nvm1 = cutlass.min(I32(15), s1 - 1 - tok0)
        tb = (tok0 * nheads + hq) * 128 + d
        l16 = cute.make_layout(16, stride=nheads * 128)
        gKc = cute.make_tensor(mK.iterator + tb, l16)
        gQc = cute.make_tensor(mQ.iterator + tb, l16)
        gVc = cute.make_tensor(mV.iterator + tb, l16)
        gGc = cute.make_tensor(mG.iterator + tb, l16)
        gBc = cute.make_tensor(mBeta.iterator + tok0 * nheads + hq, cute.make_layout(16, stride=nheads))

        kw = []
        ub = []
        qg = []
        vv = []
        cs = F32(0.0)
        ee = F32(1.0)
        for i in cutlass.range_constexpr(16):
            if cutlass.const_expr(PREP_MODE == 1):
                t = I32(i)
                msk = F32(1.0)
            else:
                t = cutlass.min(I32(i), nvm1)
                msk = F32(1.0)
                if I32(i) > nvm1:
                    msk = F32(0.0)
            kx = gKc[t].to(F32) * msk
            qx = gQc[t].to(F32) * msk
            vx = gVc[t].to(F32) * msk
            gx = gGc[t] * msk
            bx = gBc[t] * msk
            cs = cs + gx * F32(LOG2E)
            ee = cute.math.exp2(cs, fastmath=True)
            rr = cute.math.exp2(-cs, fastmath=True)
            w = kx * ee
            u = bx * kx * rr
            qw = qx * ee * F32(scale)
            kw.append(w)
            ub.append(u)
            qg.append(qw)
            vv.append(vx)
            sA[i, d] = w.to(BF16)
            sA[16 + i, d] = qw.to(BF16)
            sB[i, d] = u.to(BF16)
        for i in cutlass.range_constexpr(32, 64):
            sA[i, d] = BF16(0.0)

        aval = ee
        cute.arch.barrier()

        thr_mma = tiled_mma.get_slice(0)
        tCrA = tiled_mma.make_fragment_A(thr_mma.partition_A(sA))
        tCrB = tiled_mma.make_fragment_B(thr_mma.partition_B(sB))
        acc = cute.make_rmem_tensor(thr_mma.partition_C(cute.make_identity_tensor((64, 16))).shape, F32)
        acc.fill(0.0)
        tiled_mma.set(warpgroup.Field.ACCUMULATE, True)
        warpgroup.fence()
        for kb in cutlass.range_constexpr(8):
            cute.gemm(tiled_mma, acc, tCrA[None, None, kb], tCrB[None, None, kb], acc)
        warpgroup.commit_group()
        warpgroup.wait_group(0)

        copy_f32 = cute.make_copy_atom(cute.nvgpu.CopyUniversalOp(), F32)
        tc = cute.make_tiled_copy_C(copy_f32, tiled_mma)
        thr_tc = tc.get_slice(tidx)
        cute.autovec_copy(thr_tc.retile(acc), thr_tc.partition_D(sM))

        cute.arch.barrier()

        wt = [kw[0]]
        ut = [vv[0]]
        for i in cutlass.range_constexpr(1, 16):
            sw = kw[i]
            su = vv[i]
            for j in cutlass.range_constexpr(i):
                m = sM[i, j]
                sw = sw - m * wt[j]
                su = su - m * ut[j]
            wt.append(sw)
            ut.append(su)

        # Same trick on the store side: a constexpr-stride 1-D view per array
        # turns each of the 64 workspace stores into base-plus-immediate.
        ob = cb * 16 * 128 + d
        o16 = cute.make_layout(16, stride=128)
        oMW = cute.make_tensor(mMW.iterator + ob, o16)
        oQG = cute.make_tensor(mQG.iterator + ob, o16)
        oKG = cute.make_tensor(mKG.iterator + ob, o16)
        oUT = cute.make_tensor(mUT.iterator + ob, o16)
        for i in cutlass.range_constexpr(16):
            oMW[i] = (-wt[i]).to(BF16)
            oQG[i] = qg[i].to(BF16)
            oKG[i] = (ub[i] * aval).to(BF16)
            oUT[i] = ut[i].to(BF16)
        mAv[cb, d] = aval

        zi = tidx // 16
        zj = tidx % 16
        for r in cutlass.range_constexpr(2):
            ii = zi + r * 8
            zz = F32(0.0)
            if zj <= ii:
                zz = sM[16 + ii, zj]
            mZ[cb * 16 + ii, zj] = zz.to(BF16)


# ---------------------------------------------------------------------------
# SEGMENT kernel: BUILD (segment affine operator) or EXPAND (outputs)
#
#   chunk step (transposed state St [Dv, Dk]):
#       Rt = ut^T + St @ (-wt)^T ;  St = St*a + Rt @ kg
#   so the chunk's affine map is  St_new = St Mt_c + Ct_c  with
#       Mt_c = Diag(a) - wt^T kg  ,  Ct_c = ut^T kg
#   Composing over a segment obeys the SAME recurrence, with
#       Mt: accumulator seeded with I and no ut term
#       Ct: accumulator seeded with 0 and the ut term
#   -- i.e. one kernel body serves the operator build and the expansion.
# ---------------------------------------------------------------------------
@cute.kernel
def seg_kernel(
    mCu: cute.Tensor,
    mIS: cute.Tensor,
    mO: cute.Tensor,
    mFS: cute.Tensor,
    mSS: cute.Tensor,
    mMT: cute.Tensor,
    mCT: cute.Tensor,
    atom_mw: cute.CopyAtom,
    tMW: cute.Tensor,
    atom_qg: cute.CopyAtom,
    tQG: cute.Tensor,
    atom_kg: cute.CopyAtom,
    tKG: cute.Tensor,
    atom_ut: cute.CopyAtom,
    tUT: cute.Tensor,
    atom_z: cute.CopyAtom,
    tZ: cute.Tensor,
    atom_av: cute.CopyAtom,
    tAV: cute.Tensor,
    mma_s: cute.TiledMma,
    mma_n: cute.TiledMma,
    nch: cutlass.Constexpr,
    nheads: cutlass.Constexpr,
    NSEG: cutlass.Constexpr,
    MODE: cutlass.Constexpr,
    VSLAB: cutlass.Constexpr,
):
    DUAL_BUILD = cutlass.const_expr(MODE == 3)
    BUILD = cutlass.const_expr(MODE != 2)
    WHICH = cutlass.const_expr(1 if MODE != 0 else 0)
    TXB = cutlass.const_expr(8704 + (4096 // VSLAB if MODE >= 1 else 0) + (4608 if MODE == 2 else 0))
    tidx, _, _ = cute.arch.thread_idx()
    segv, hq, zz = cute.arch.block_idx()
    seg = segv // VSLAB
    vs = segv % VSLAB
    vm = cutlass.const_expr(DIM // VSLAB)
    v0 = vs * vm
    warp_idx = cute.arch.make_warp_uniform(cute.arch.warp_idx())

    if warp_idx == 0:
        cpasync.prefetch_descriptor(atom_mw)
        cpasync.prefetch_descriptor(atom_kg)
        cpasync.prefetch_descriptor(atom_av)
        if cutlass.const_expr(MODE >= 1):
            cpasync.prefetch_descriptor(atom_ut)
        if cutlass.const_expr(MODE == 2):
            cpasync.prefetch_descriptor(atom_qg)
            cpasync.prefetch_descriptor(atom_z)

    sq = zz

    s0 = mCu[sq]
    s1 = mCu[sq + 1]
    ncsq = (s1 - s0 + 15) // 16
    seglen = (ncsq + (NSEG - 1)) // NSEG
    c0 = cutlass.min(seg * seglen, ncsq)
    c1 = cutlass.min(c0 + seglen, ncsq)
    ncs = c1 - c0
    cb = (s0 // 16 + sq + c0) * nheads + hq
    opi = (sq * nheads + hq) * NSEG + seg

    sMW_l = hh.make_smem_layout_b(utils.LayoutEnum.ROW_MAJOR, (128, 16, 128), BF16, NSTAGE)
    sKG_l = hh.make_smem_layout_b(utils.LayoutEnum.COL_MAJOR, (128, 128, 16), BF16, NSTAGE)
    sZ_l = hh.make_smem_layout_b(utils.LayoutEnum.ROW_MAJOR, (128, 16, 16), BF16, NSTAGE)
    sUT_l = hh.make_smem_layout_b(utils.LayoutEnum.COL_MAJOR, (vm, vm, 16), BF16, NSTAGE)
    sAV_l = cute.make_layout((1, 128, NSTAGE), stride=(128, 1, 128))

    smem = utils.SmemAllocator()
    mbar = smem.allocate_array(cutlass.Int64, NSTAGE * 2, byte_alignment=16)
    sMW = smem.allocate_tensor(BF16, sMW_l.outer, byte_alignment=1024, swizzle=sMW_l.inner)
    sQG = smem.allocate_tensor(BF16, sMW_l.outer, byte_alignment=1024, swizzle=sMW_l.inner)
    sKG = smem.allocate_tensor(BF16, sKG_l.outer, byte_alignment=1024, swizzle=sKG_l.inner)
    sZ = smem.allocate_tensor(BF16, sZ_l.outer, byte_alignment=1024, swizzle=sZ_l.inner)
    sUT = smem.allocate_tensor(BF16, sUT_l.outer, byte_alignment=1024, swizzle=sUT_l.inner)
    sAV = smem.allocate_tensor(F32, sAV_l, byte_alignment=1024)

    pipe = pipeline.PipelineTmaAsync.create(
        barrier_storage=mbar,
        num_stages=NSTAGE,
        producer_group=pipeline.CooperativeGroup(pipeline.Agent.Thread),
        consumer_group=pipeline.CooperativeGroup(pipeline.Agent.Warp, 8 // VSLAB),
        tx_count=TXB,
        cta_layout_vmnk=cute.make_layout((1, 1, 1, 1)),
        enable_multicast_signaling=True,
    )

    cta1 = cute.make_layout(1)
    gMW = cute.local_tile(tMW, (16, 128), (None, 0))
    gQG = cute.local_tile(tQG, (16, 128), (None, 0))
    gKG = cute.local_tile(tKG, (128, 16), (0, None))
    if cutlass.const_expr(VSLAB == 1):
        gUT = cute.local_tile(tUT, (128, 16), (0, None))
    else:
        gUT = cute.local_tile(tUT, (vm, 16), (vs, None))
    gZ = cute.local_tile(tZ, (16, 16), (None, 0))
    gAV = cute.local_tile(tAV, (1, 128), (None, 0))

    aMWs, aMWg = cpasync.tma_partition(atom_mw, 0, cta1, cute.group_modes(sMW, 0, 2), cute.group_modes(gMW, 0, 2))
    aQGs, aQGg = cpasync.tma_partition(atom_qg, 0, cta1, cute.group_modes(sQG, 0, 2), cute.group_modes(gQG, 0, 2))
    aKGs, aKGg = cpasync.tma_partition(atom_kg, 0, cta1, cute.group_modes(sKG, 0, 2), cute.group_modes(gKG, 0, 2))
    aUTs, aUTg = cpasync.tma_partition(atom_ut, 0, cta1, cute.group_modes(sUT, 0, 2), cute.group_modes(gUT, 0, 2))
    aZs, aZg = cpasync.tma_partition(atom_z, 0, cta1, cute.group_modes(sZ, 0, 2), cute.group_modes(gZ, 0, 2))
    aAVs, aAVg = cpasync.tma_partition(atom_av, 0, cta1, cute.group_modes(sAV, 0, 2), cute.group_modes(gAV, 0, 2))

    wgi = cute.arch.make_warp_uniform(tidx // 128)
    wg_layout = cute.make_layout(2 // VSLAB, stride=128)
    thr_s = mma_s.get_slice(wg_layout(wgi))
    thr_n = mma_n.get_slice(wg_layout(wgi))

    accS = cute.make_rmem_tensor(thr_s.partition_C(cute.make_identity_tensor((vm, 128))).shape, F32)
    accC = cute.make_rmem_tensor_like(accS)
    accR = cute.make_rmem_tensor(thr_n.partition_C(cute.make_identity_tensor((vm, 16))).shape, F32)
    accO = cute.make_rmem_tensor(thr_n.partition_C(cute.make_identity_tensor((vm, 16))).shape, F32)

    copy_f32 = cute.make_copy_atom(cute.nvgpu.CopyUniversalOp(), F32)
    tcS = cute.make_tiled_copy_C(copy_f32, mma_s)
    thr_tcS = tcS.get_slice(tidx)
    tcN = cute.make_tiled_copy_C(copy_f32, mma_n)
    thr_tcN = tcN.get_slice(tidx)

    cS = thr_tcS.partition_D(cute.make_identity_tensor((vm, 128)))
    cO = thr_tcN.partition_D(cute.make_identity_tensor((vm, 16)))
    tAccS = thr_tcS.retile(accS)
    tAccC = thr_tcS.retile(accC)
    tAccR = thr_tcN.retile(accR)
    tAccO = thr_tcN.retile(accO)

    if cutlass.const_expr(BUILD):
        accS.fill(0.0)
        if cutlass.const_expr(WHICH == 0):
            for e in cutlass.range_constexpr(cute.size(tAccS)):
                if cS[e][0] == cS[e][1]:
                    tAccS[e] = F32(1.0)
        elif cutlass.const_expr(DUAL_BUILD):
            for e in cutlass.range_constexpr(cute.size(tAccS)):
                if cS[e][0] == cS[e][1]:
                    tAccS[e] = F32(1.0)
        if cutlass.const_expr(DUAL_BUILD):
            accC.fill(0.0)
    else:
        if cutlass.const_expr(NSEG == 1):
            if cutlass.const_expr(VSLAB == 1):
                cute.autovec_copy(thr_tcS.partition_D(mIS[sq, hq, None, None]), tAccS)
            else:
                state_l = cute.make_layout((vm, 128), stride=(128, 1))
                gIS = cute.make_tensor(mIS[sq, hq, None, None].iterator + v0 * 128, state_l)
                cute.autovec_copy(thr_tcS.partition_D(gIS), tAccS)
        else:
            cute.autovec_copy(thr_tcS.partition_D(mSS[opi, None, None]), tAccS)

    prod = pipeline.make_pipeline_state(pipeline.PipelineUserType.Producer, NSTAGE)
    cons = pipeline.make_pipeline_state(pipeline.PipelineUserType.Consumer, NSTAGE)

    npre = cutlass.min(I32(NSTAGE), ncs)
    if warp_idx == 0:
        for pi in cutlass.range(npre, unroll=1):
            pipe.producer_acquire(prod)
            bp = pipe.producer_get_barrier(prod)
            ti = cb + prod.count * nheads
            si = prod.index
            cute.copy(atom_mw, aMWg[(None, ti)], aMWs[(None, si)], tma_bar_ptr=bp)
            cute.copy(atom_kg, aKGg[(None, ti)], aKGs[(None, si)], tma_bar_ptr=bp)
            cute.copy(atom_av, aAVg[(None, ti)], aAVs[(None, si)], tma_bar_ptr=bp)
            if cutlass.const_expr(MODE >= 1):
                cute.copy(atom_ut, aUTg[(None, ti)], aUTs[(None, si)], tma_bar_ptr=bp)
            if cutlass.const_expr(MODE == 2):
                cute.copy(atom_qg, aQGg[(None, ti)], aQGs[(None, si)], tma_bar_ptr=bp)
                cute.copy(atom_z, aZg[(None, ti)], aZs[(None, si)], tma_bar_ptr=bp)
            prod.advance()

    mma_s.set(warpgroup.Field.ACCUMULATE, True)
    mma_n.set(warpgroup.Field.ACCUMULATE, True)
    a_shape_n = mma_n.tv_layout_A.shape[1]

    for ci in cutlass.range(ncs, unroll=1):
        pipe.consumer_wait(cons)
        st = cons.index
        tok0 = s0 + (c0 + ci) * 16

        tMWr = mma_n.make_fragment_B(thr_n.partition_B(sMW[None, None, st]))

        if cutlass.const_expr(DUAL_BUILD):
            aMt = acc_to_a(accS, a_shape_n)
            aCt = acc_to_a(accC, a_shape_n)
            for e in cutlass.range_constexpr(cute.size(tAccS)):
                av = sAV[0, cS[e][1], st]
                tAccS[e] = tAccS[e] * av
                tAccC[e] = tAccC[e] * av

            accR.fill(0.0)
            accO.fill(0.0)
            warpgroup.fence()
            for kb in cutlass.range_constexpr(8):
                cute.gemm(
                    mma_n,
                    accR,
                    aMt[None, None, kb],
                    tMWr[None, None, kb],
                    accR,
                )
            warpgroup.commit_group()

            for kb in cutlass.range_constexpr(8):
                cute.gemm(
                    mma_n,
                    accO,
                    aCt[None, None, kb],
                    tMWr[None, None, kb],
                    accO,
                )
            warpgroup.commit_group()
            warpgroup.wait_group(0)

            rUT = cute.make_rmem_tensor_like(tAccO, BF16)
            cute.autovec_copy(thr_tcN.partition_D(sUT[None, None, st]), rUT)
            tAccO.store(tAccO.load() + rUT.load().to(F32))

            aRMt = acc_to_a(accR, a_shape_n)
            aRCt = acc_to_a(accO, a_shape_n)
            tKGr = mma_s.make_fragment_B(thr_s.partition_B(sKG[None, None, st]))
            warpgroup.fence()
            cute.gemm(
                mma_s,
                accS,
                aRMt[None, None, 0],
                tKGr[None, None, 0],
                accS,
            )
            cute.gemm(
                mma_s,
                accC,
                aRCt[None, None, 0],
                tKGr[None, None, 0],
                accC,
            )
            warpgroup.commit_group()
            warpgroup.wait_group(0)
        else:
            sAVb = cute.make_tensor(
                sAV[0, None, st].iterator,
                cute.make_layout((vm, 128), stride=(0, 1)),
            )
            rAv = cute.make_rmem_tensor_like(tAccS, F32)
            cute.autovec_copy(thr_tcS.partition_D(sAVb), rAv)
            accR.fill(0.0)
            if cutlass.const_expr(WHICH == 1):
                rUT = cute.make_rmem_tensor_like(tAccR, BF16)
                cute.autovec_copy(thr_tcN.partition_D(sUT[None, None, st]), rUT)
                tAccR.store(rUT.load().to(F32))

            aSt = acc_to_a(accS, a_shape_n)
            tAccS.store(tAccS.load() * rAv.load())

            warpgroup.fence()
            for kb in cutlass.range_constexpr(8):
                cute.gemm(
                    mma_n,
                    accR,
                    aSt[None, None, kb],
                    tMWr[None, None, kb],
                    accR,
                )
            warpgroup.commit_group()
            if cutlass.const_expr(not BUILD):
                accO.fill(0.0)
                tQGr = mma_n.make_fragment_B(thr_n.partition_B(sQG[None, None, st]))
                warpgroup.fence()
                for kb in cutlass.range_constexpr(8):
                    cute.gemm(
                        mma_n,
                        accO,
                        aSt[None, None, kb],
                        tQGr[None, None, kb],
                        accO,
                    )
                warpgroup.commit_group()
                warpgroup.wait_group(1)
            else:
                warpgroup.wait_group(0)

            aRt = acc_to_a(accR, a_shape_n)
            tKGr = mma_s.make_fragment_B(thr_s.partition_B(sKG[None, None, st]))
            warpgroup.fence()
            if cutlass.const_expr(not BUILD):
                tZr = mma_n.make_fragment_B(thr_n.partition_B(sZ[None, None, st]))
                cute.gemm(mma_n, accO, aRt[None, None, 0], tZr[None, None, 0], accO)
            cute.gemm(mma_s, accS, aRt[None, None, 0], tKGr[None, None, 0], accS)
            warpgroup.commit_group()
            warpgroup.wait_group(0)

        pipe.consumer_release(cons)
        cons.advance()

        if cutlass.const_expr(not BUILD):
            rO = cute.make_rmem_tensor_like(tAccO, BF16)
            rO.store(tAccO.load().to(BF16))
            for e in cutlass.range_constexpr(cute.size(tAccO)):
                tt = tok0 + cO[e][1]
                if tt < s1:
                    if cutlass.const_expr(VSLAB == 1):
                        mO[tt, hq, cO[e][0]] = rO[e]
                    else:
                        mO[tt, hq, v0 + cO[e][0]] = rO[e]

        nxt = ci + NSTAGE
        if warp_idx == 0:
            if nxt < ncs:
                pipe.producer_acquire(prod)
                bp = pipe.producer_get_barrier(prod)
                ti = cb + nxt * nheads
                si = prod.index
                cute.copy(atom_mw, aMWg[(None, ti)], aMWs[(None, si)], tma_bar_ptr=bp)
                cute.copy(atom_kg, aKGg[(None, ti)], aKGs[(None, si)], tma_bar_ptr=bp)
                cute.copy(atom_av, aAVg[(None, ti)], aAVs[(None, si)], tma_bar_ptr=bp)
                if cutlass.const_expr(MODE >= 1):
                    cute.copy(atom_ut, aUTg[(None, ti)], aUTs[(None, si)], tma_bar_ptr=bp)
                if cutlass.const_expr(MODE == 2):
                    cute.copy(atom_qg, aQGg[(None, ti)], aQGs[(None, si)], tma_bar_ptr=bp)
                    cute.copy(atom_z, aZg[(None, ti)], aZs[(None, si)], tma_bar_ptr=bp)
                prod.advance()

    if cutlass.const_expr(BUILD):
        if cutlass.const_expr(DUAL_BUILD):
            rM = cute.make_rmem_tensor_like(tAccS, BF16)
            rM.store(tAccS.load().to(BF16))
            cute.autovec_copy(rM, thr_tcS.partition_D(mMT[opi, None, None]))
            cute.autovec_copy(tAccC, thr_tcS.partition_D(mCT[opi, None, None]))
        elif cutlass.const_expr(WHICH == 0):
            rM = cute.make_rmem_tensor_like(tAccS, BF16)
            rM.store(tAccS.load().to(BF16))
            cute.autovec_copy(rM, thr_tcS.partition_D(mMT[opi, None, None]))
        else:
            cute.autovec_copy(tAccS, thr_tcS.partition_D(mCT[opi, None, None]))
    else:
        if c1 == ncsq:
            if cutlass.const_expr(VSLAB == 1):
                cute.autovec_copy(tAccS, thr_tcS.partition_D(mFS[sq, hq, None, None]))
            else:
                state_l = cute.make_layout((vm, 128), stride=(128, 1))
                gFS = cute.make_tensor(mFS[sq, hq, None, None].iterator + v0 * 128, state_l)
                cute.autovec_copy(tAccS, thr_tcS.partition_D(gFS))


# ---------------------------------------------------------------------------
# COMBINE: short serial scan over the NSEG segment operators, split into eight
# independent V-row slabs.  For one 16-row slab X = S[v:v+16, :], compute
#     X_new^T = Mt^T X^T + Ct[v:v+16, :]^T
# as an m128n16 WGMMA.
#
# Mt^T is fed as an MN-MAJOR SMEM A operand staged by TMA.  Mt is written
# row-major [Kin, Kout] by BUILD, so "M contiguous" already *is* the transpose
# -- no data movement is needed to turn Mt into Mt^T, and the 32 KB operator
# arrives as one coalesced bulk copy instead of 16384 strided 2-byte LDGs into
# a register A fragment (which is what pinned this kernel at 88% L1 throughput
# and IPC 0.25).
# ---------------------------------------------------------------------------
@cute.kernel
def comb_kernel(
    mIS: cute.Tensor,
    mSS: cute.Tensor,
    mCT: cute.Tensor,
    atom_mt: cute.CopyAtom,
    tMT: cute.Tensor,
    mma_v: cute.TiledMma,
    nheads: cutlass.Constexpr,
    NSEG: cutlass.Constexpr,
):
    tidx, _, _ = cute.arch.thread_idx()
    sq, hq, vs = cute.arch.block_idx()
    v0 = vs * (DIM // VSPLIT)
    warp_idx = cute.arch.make_warp_uniform(cute.arch.warp_idx())

    if warp_idx == 0:
        cpasync.prefetch_descriptor(atom_mt)

    sA_l = hh.make_smem_layout_a(utils.LayoutEnum.COL_MAJOR, (128, DIM // VSPLIT, 128), BF16, NSTC)
    sX_l = cute.slice_(
        hh.make_smem_layout_b(utils.LayoutEnum.COL_MAJOR, (128, DIM // VSPLIT, 128), BF16, 1),
        (None, None, 0),
    )
    smem = utils.SmemAllocator()
    mbar = smem.allocate_array(cutlass.Int64, NSTC * 2, byte_alignment=16)
    sMt = smem.allocate_tensor(BF16, sA_l.outer, byte_alignment=1024, swizzle=sA_l.inner)
    sX = smem.allocate_tensor(BF16, sX_l.outer, byte_alignment=1024, swizzle=sX_l.inner)

    pipe = pipeline.PipelineTmaAsync.create(
        barrier_storage=mbar,
        num_stages=NSTC,
        producer_group=pipeline.CooperativeGroup(pipeline.Agent.Thread),
        consumer_group=pipeline.CooperativeGroup(pipeline.Agent.Warp, 8),
        tx_count=128 * 128 * 2,
        cta_layout_vmnk=cute.make_layout((1, 1, 1, 1)),
        enable_multicast_signaling=True,
    )
    cta1 = cute.make_layout(1)
    gMT = cute.local_tile(tMT, (128, 128), (0, None))
    aMTs, aMTg = cpasync.tma_partition(atom_mt, 0, cta1, cute.group_modes(sMt, 0, 2), cute.group_modes(gMT, 0, 2))

    wgi = cute.arch.make_warp_uniform(tidx // 128)
    thr_v = mma_v.get_slice(cute.make_layout(2, stride=128)(wgi))
    accX = cute.make_rmem_tensor(thr_v.partition_C(cute.make_identity_tensor((128, DIM // VSPLIT))).shape, F32)

    copy_f32 = cute.make_copy_atom(cute.nvgpu.CopyUniversalOp(), F32)
    tcV = cute.make_tiled_copy_C(copy_f32, mma_v)
    thr_tcV = tcV.get_slice(tidx)
    tAccX = thr_tcV.retile(accX)
    cX = thr_tcV.partition_D(cute.make_identity_tensor((128, DIM // VSPLIT)))
    rX = cute.make_rmem_tensor_like(tAccX, BF16)
    rC0 = cute.make_rmem_tensor_like(tAccX, F32)
    rC1 = cute.make_rmem_tensor_like(tAccX, F32)

    base = (sq * nheads + hq) * NSEG
    mma_v.set(warpgroup.Field.ACCUMULATE, True)
    trans_l = cute.make_layout((128, DIM // VSPLIT), stride=(1, 128))

    gIS = cute.make_tensor(mIS[sq, hq, None, None].iterator + v0 * 128, trans_l)
    cute.autovec_copy(thr_tcV.partition_D(gIS), tAccX)
    # The additive operator C is an ordinary LDG, so it must be fetched a step
    # ahead; otherwise its ~700 ns latency lands directly on the serial combine
    # chain once per segment.
    if cutlass.const_expr(NSEG > 1):
        cute.autovec_copy(
            thr_tcV.partition_D(cute.make_tensor(mCT[base, None, None].iterator + v0 * 128, trans_l)),
            rC0,
        )

    prod = pipeline.make_pipeline_state(pipeline.PipelineUserType.Producer, NSTC)
    cons = pipeline.make_pipeline_state(pipeline.PipelineUserType.Consumer, NSTC)
    npre = cutlass.const_expr(min(NSTC, NSEG - 1))
    if warp_idx == 0:
        for pi in cutlass.range_constexpr(npre):
            pipe.producer_acquire(prod)
            bp = pipe.producer_get_barrier(prod)
            cute.copy(
                atom_mt,
                aMTg[(None, base + pi)],
                aMTs[(None, prod.index)],
                tma_bar_ptr=bp,
            )
            prod.advance()

    tXr = mma_v.make_fragment_B(thr_v.partition_B(sX))

    for p in cutlass.range_constexpr(NSEG):
        gSS = cute.make_tensor(mSS[base + p, None, None].iterator + v0 * 128, trans_l)
        cute.autovec_copy(tAccX, thr_tcV.partition_D(gSS))

        if cutlass.const_expr(p + 1 < NSEG):
            if cutlass.const_expr(p + 1 < NSEG - 1):
                gCn = cute.make_tensor(mCT[base + p + 1, None, None].iterator + v0 * 128, trans_l)
                if cutlass.const_expr(p % 2 == 0):
                    cute.autovec_copy(thr_tcV.partition_D(gCn), rC1)
                else:
                    cute.autovec_copy(thr_tcV.partition_D(gCn), rC0)
            rX.store(tAccX.load().to(BF16))
            cute.arch.barrier()
            for e in cutlass.range_constexpr(cute.size(rX)):
                sX[cX[e][1], cX[e][0]] = rX[e]
            cute.arch.fence_view_async_shared()
            cute.arch.barrier()

            if cutlass.const_expr(p % 2 == 0):
                tAccX.store(rC0.load())
            else:
                tAccX.store(rC1.load())

            pipe.consumer_wait(cons)
            st = cons.index
            tMr = mma_v.make_fragment_A(thr_v.partition_A(sMt[None, None, st]))
            warpgroup.fence()
            for kb in cutlass.range_constexpr(8):
                cute.gemm(mma_v, accX, tMr[None, None, kb], tXr[None, None, kb], accX)
            warpgroup.commit_group()
            warpgroup.wait_group(0)
            pipe.consumer_release(cons)
            cons.advance()

            if warp_idx == 0:
                if cutlass.const_expr(p + NSTC < NSEG - 1):
                    pipe.producer_acquire(prod)
                    bp = pipe.producer_get_barrier(prod)
                    cute.copy(
                        atom_mt,
                        aMTg[(None, base + p + NSTC)],
                        aMTs[(None, prod.index)],
                        tma_bar_ptr=bp,
                    )
                    prod.advance()


# ---------------------------------------------------------------------------
# host
# ---------------------------------------------------------------------------
@cute.jit
def kda_launch(
    mQ: cute.Tensor,
    mK: cute.Tensor,
    mV: cute.Tensor,
    mG: cute.Tensor,
    mBeta: cute.Tensor,
    mCu: cute.Tensor,
    mIS: cute.Tensor,
    mMW: cute.Tensor,
    mQG: cute.Tensor,
    mKG: cute.Tensor,
    mUT: cute.Tensor,
    mZ: cute.Tensor,
    mAv: cute.Tensor,
    mKGt: cute.Tensor,
    mUTt: cute.Tensor,
    mSS: cute.Tensor,
    mMT: cute.Tensor,
    mMTt: cute.Tensor,
    mCT: cute.Tensor,
    mO: cute.Tensor,
    mFS: cute.Tensor,
    nseq: cutlass.Constexpr,
    nheads: cutlass.Constexpr,
    prep_nch: cutlass.Constexpr,
    nch: cutlass.Constexpr,
    nseg: cutlass.Constexpr,
    stream: cudadrv.CUstream,
):
    scale = 1.0 / math.sqrt(DIM)

    mma_p = hh.make_trivial_tiled_mma(
        BF16,
        BF16,
        cute.nvgpu.OperandMajorMode.K,
        cute.nvgpu.OperandMajorMode.K,
        F32,
        (1, 1, 1),
        tiler_mn=(64, 16),
    )
    if cutlass.const_expr(nseq == 1 and prep_nch < 512):
        prep_kernel(
            mQ,
            mK,
            mV,
            mG,
            mBeta,
            mCu,
            mMW,
            mQG,
            mKG,
            mUT,
            mZ,
            mAv,
            mma_p,
            scale,
            nseq,
            nch,
            nheads,
            0,
        ).launch(grid=[nheads, prep_nch], block=[128, 1, 1], stream=stream)
    else:
        prep_kernel(
            mQ,
            mK,
            mV,
            mG,
            mBeta,
            mCu,
            mMW,
            mQG,
            mKG,
            mUT,
            mZ,
            mAv,
            mma_p,
            scale,
            nseq,
            nch,
            nheads,
            1,
        ).launch(grid=[nheads, prep_nch], block=[128, 1, 1], stream=stream)
        prep_kernel(
            mQ,
            mK,
            mV,
            mG,
            mBeta,
            mCu,
            mMW,
            mQG,
            mKG,
            mUT,
            mZ,
            mAv,
            mma_p,
            scale,
            nseq,
            nch,
            nheads,
            2,
        ).launch(grid=[nheads, nseq], block=[128, 1, 1], stream=stream)

    mma_s = hh.make_trivial_tiled_mma(
        BF16,
        BF16,
        cute.nvgpu.OperandMajorMode.K,
        cute.nvgpu.OperandMajorMode.MN,
        F32,
        (2, 1, 1),
        tiler_mn=(64, 128),
        a_source=warpgroup.OperandSource.RMEM,
    )
    mma_n = hh.make_trivial_tiled_mma(
        BF16,
        BF16,
        cute.nvgpu.OperandMajorMode.K,
        cute.nvgpu.OperandMajorMode.K,
        F32,
        (2, 1, 1),
        tiler_mn=(64, 16),
        a_source=warpgroup.OperandSource.RMEM,
    )

    sMW_1 = cute.slice_(hh.make_smem_layout_b(utils.LayoutEnum.ROW_MAJOR, (128, 16, 128), BF16, NSTAGE), (None, None, 0))
    sKG_1 = cute.slice_(hh.make_smem_layout_b(utils.LayoutEnum.COL_MAJOR, (128, 128, 16), BF16, NSTAGE), (None, None, 0))
    sZ_1 = cute.slice_(hh.make_smem_layout_b(utils.LayoutEnum.ROW_MAJOR, (128, 16, 16), BF16, NSTAGE), (None, None, 0))
    sAV_1 = cute.make_layout((1, 128), stride=(128, 1))

    op = cpasync.CopyBulkTensorTileG2SOp()
    atom_mw, tMW = cpasync.make_tiled_tma_atom(op, mMW, sMW_1, (16, 128))
    atom_qg, tQG = cpasync.make_tiled_tma_atom(op, mQG, sMW_1, (16, 128))
    atom_kg, tKG = cpasync.make_tiled_tma_atom(op, mKGt, sKG_1, (128, 16))
    atom_ut, tUT = cpasync.make_tiled_tma_atom(op, mUTt, sKG_1, (128, 16))
    atom_z, tZ = cpasync.make_tiled_tma_atom(op, mZ, sZ_1, (16, 16))
    atom_av, tAV = cpasync.make_tiled_tma_atom(op, mAv, sAV_1, (1, 128))

    if cutlass.const_expr(nseg > 1):
        seg_kernel(
            mCu,
            mIS,
            mO,
            mFS,
            mSS,
            mMT,
            mCT,
            atom_mw,
            tMW,
            atom_qg,
            tQG,
            atom_kg,
            tKG,
            atom_ut,
            tUT,
            atom_z,
            tZ,
            atom_av,
            tAV,
            mma_s,
            mma_n,
            nch,
            nheads,
            nseg,
            3,
            1,
        ).launch(grid=[nseg - 1, nheads, nseq], block=[256, 1, 1], stream=stream)
        # COMBINE chains operators 0..NSEG-2 only: the last segment's affine
        # operator is never read, so BUILD skips it entirely.

        mma_v = hh.make_trivial_tiled_mma(
            BF16,
            BF16,
            cute.nvgpu.OperandMajorMode.MN,
            cute.nvgpu.OperandMajorMode.MN,
            F32,
            (2, 1, 1),
            tiler_mn=(64, DIM // VSPLIT),
        )
        sMT_1 = cute.slice_(
            hh.make_smem_layout_a(utils.LayoutEnum.COL_MAJOR, (128, DIM // VSPLIT, 128), BF16, NSTC),
            (None, None, 0),
        )
        atom_mt, tMT = cpasync.make_tiled_tma_atom(op, mMTt, sMT_1, (128, 128))
        comb_kernel(
            mIS,
            mSS,
            mCT,
            atom_mt,
            tMT,
            mma_v,
            nheads,
            nseg,
        ).launch(grid=[nseq, nheads, VSPLIT], block=[256, 1, 1], stream=stream)

    if cutlass.const_expr(nseg == 1):
        sUT_1_v = cute.slice_(
            hh.make_smem_layout_b(
                utils.LayoutEnum.COL_MAJOR,
                (DIM // 2, DIM // 2, 16),
                BF16,
                NSTAGE,
            ),
            (None, None, 0),
        )
        atom_ut_v, tUT_v = cpasync.make_tiled_tma_atom(op, mUTt, sUT_1_v, (DIM // 2, 16))
        mma_s_v = hh.make_trivial_tiled_mma(
            BF16,
            BF16,
            cute.nvgpu.OperandMajorMode.K,
            cute.nvgpu.OperandMajorMode.MN,
            F32,
            (1, 1, 1),
            tiler_mn=(64, 128),
            a_source=warpgroup.OperandSource.RMEM,
        )
        mma_n_v = hh.make_trivial_tiled_mma(
            BF16,
            BF16,
            cute.nvgpu.OperandMajorMode.K,
            cute.nvgpu.OperandMajorMode.K,
            F32,
            (1, 1, 1),
            tiler_mn=(64, 16),
            a_source=warpgroup.OperandSource.RMEM,
        )
        seg_kernel(
            mCu,
            mIS,
            mO,
            mFS,
            mSS,
            mMT,
            mCT,
            atom_mw,
            tMW,
            atom_qg,
            tQG,
            atom_kg,
            tKG,
            atom_ut_v,
            tUT_v,
            atom_z,
            tZ,
            atom_av,
            tAV,
            mma_s_v,
            mma_n_v,
            nch,
            nheads,
            nseg,
            2,
            2,
        ).launch(grid=[2, nheads, nseq], block=[128, 1, 1], stream=stream)
    else:
        seg_kernel(
            mCu,
            mIS,
            mO,
            mFS,
            mSS,
            mMT,
            mCT,
            atom_mw,
            tMW,
            atom_qg,
            tQG,
            atom_kg,
            tKG,
            atom_ut,
            tUT,
            atom_z,
            tZ,
            atom_av,
            tAV,
            mma_s,
            mma_n,
            nch,
            nheads,
            nseg,
            2,
            1,
        ).launch(grid=[nseg, nheads, nseq], block=[256, 1, 1], stream=stream)


_CACHE = {}
_WS = {}


def _pick_nseg(T, N, H):
    """Pick the segment count from a measured cost model of the three phases.

    BUILD/EXPAND cost is (fixed + seglen * per_step); COMBINE is a serial scan
    over the NSEG operators.  Segments are capped so BUILD/EXPAND stay inside a
    single 132-SM wave.  The single-segment path skips BUILD and COMBINE
    entirely and reads the workspace once, so it gets a margin before a
    segmented schedule is allowed to take over.
    """
    L = T // max(N, 1)
    ncs = (L + 15) // 16
    pmax = min(132 // max(N * H, 1), max(ncs // 2, 1))
    best = 1
    bestc = (9.5 + ncs * 1.215) * 0.93
    for p in range(2, pmax + 1):
        sl = (ncs + p - 1) // p
        c = (6.2 + sl * 1.009) + (9.5 + sl * 1.215) + (1.5 + p * 1.35)
        if c < bestc:
            bestc, best = c, p
    return best


def _ws(nch, H, N, nseg, device):
    """Scratch buffers for one shape, returned as ALREADY-CONVERTED CuTe tensors.

    These twelve buffers are keyed by shape and never change identity, so
    re-running ``from_dlpack`` on them at every launch is pure overhead -- it was
    12 of the 21 conversions per call, and DLPack conversion dominated this
    kernel's host time. Convert once here; only the caller's own operands need
    per-call conversion. The torch buffers stay alive in the cache entry because
    the CuTe tensors borrow their memory rather than owning it.
    """
    key = (nch, H, N, nseg, str(device))
    w = _WS.get(key)
    if w is None:
        c = nch * H
        kg = torch.empty((c * 16, 128), dtype=torch.bfloat16, device=device)
        ut = torch.empty((c * 16, 128), dtype=torch.bfloat16, device=device)
        nop = max(N * H * nseg, 1)
        mt = torch.empty((nop, 128, 128), dtype=torch.bfloat16, device=device)
        w = (
            torch.empty((c * 16, 128), dtype=torch.bfloat16, device=device),
            torch.empty((c * 16, 128), dtype=torch.bfloat16, device=device),
            kg,
            ut,
            torch.empty((c * 16, 16), dtype=torch.bfloat16, device=device),
            torch.empty((c, 128), dtype=torch.float32, device=device),
            kg.t(),
            ut.t(),
            torch.empty((nop, 128, 128), dtype=torch.float32, device=device),
            mt,
            mt.reshape(nop * 128, 128).t(),
            torch.empty((nop, 128, 128), dtype=torch.float32, device=device),
        )
        w = (w, tuple(from_dlpack(b, assumed_align=16) for b in w))
        _WS[key] = w
    return w[1]


def run(q, k, v, g, beta, cu_seqlens, initial_state, o, final_state):
    """Launch from torch tensors (standalone / test entry point).

    Converts the nine operands to CuTe tensors and defers to :func:`run_cute`.
    A caller that already holds CuTe tensors -- cuDNN's engine reaches them
    straight off the variant pack -- should call that directly and skip the
    torch round trip, which is two DLPack conversions per operand rather than
    one.
    """
    T, H, D = q.shape
    N = initial_state.shape[0]
    run_cute(
        from_dlpack(q, assumed_align=16),
        from_dlpack(k, assumed_align=16),
        from_dlpack(v, assumed_align=16),
        from_dlpack(g, assumed_align=16),
        from_dlpack(beta, assumed_align=16),
        from_dlpack(cu_seqlens, assumed_align=4),
        from_dlpack(initial_state, assumed_align=16),
        from_dlpack(o, assumed_align=16),
        from_dlpack(final_state, assumed_align=16),
        T,
        H,
        D,
        N,
        q.device,
        torch.cuda.current_stream().cuda_stream,
    )


def run_cute(mQ, mK, mV, mG, mB, mCu, mIS, mO, mFS, T, H, D, N, device, stream_ptr):
    """Launch from already-converted CuTe tensors on an explicit stream.

    ``stream_ptr`` is a raw CUDA stream handle, so the caller does not have to
    push a torch stream context just so this function can read it back out of
    thread-local state.
    """
    nch = T // 16 + N + 1
    prep_nch = (T + 15) // 16 + N - 1
    nseg = _pick_nseg(T, N, H)

    # Already CuTe tensors, converted once per shape (see _ws).
    ws = _ws(nch, H, N, nseg, device)

    key = (T, H, N, D)
    fn = _CACHE.get(key)
    stream = cudadrv.CUstream(stream_ptr)

    args = (mQ, mK, mV, mG, mB, mCu, mIS, *ws, mO, mFS)
    if fn is None:
        fn = cute.compile(kda_launch, *args, N, H, prep_nch, nch, nseg, stream)
        _CACHE[key] = fn
    fn(*args, stream)
